### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by tspaeth**
Fixes 404 Link to quickstart

### CODE REVIEW

**Comment by artembilan** [comment]
Hello, @tspaeth !

Thank you for the fix.
Merging it as is, but for the future be sure to sign the [CLA](https://github.com/spring-guides/getting-started-guides/wiki) to contribute properly.

**Comment by tspaeth** [comment]
Ah, thanks. Was already looking for this, but didn't look in the main repo :-)

**Comment by tspaeth** [comment]
@artembilan Which Project to choose from - AMQP? and project lead is you?

**Comment by artembilan** [comment]
M-m-m. It would be better to choose `Spring-Guide`, but I see there is no such a project.
So, yes `Spring AMQP` would be enough. As a Project Lead, please type "Gary Russell".

That's it.

**Pull request merged**
