### PR TITLE
Display extracted Runner class in README.adoc

### PR DESCRIPTION
**Pull request by thefetts**
Functionality was extracted out of Application.java in this commit:
https://github.com/spring-guides/gs-messaging-rabbitmq/commit/16fea381f9a655a4357585bda80163fce84e2b6a

This adds a reference to the new Runner class to README.adoc so people following along with this guide know they need to create it for sending messages.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thefetts Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-messaging-rabbitmq&pullRequestId=13)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-messaging-rabbitmq&pullRequestId=13) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@thefetts Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-messaging-rabbitmq&pullRequestId=13)!

**Comment by dsyer** [comment]
Thanks for the suggestion. I implemented it slightly differently: 2942500

**Comment by thefetts** [comment]
Looks great, thank you!

**Pull request closed without merging**
